# Generated by Django 3.1.2 on 2020-10-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('molestia_principal', models.CharField(max_length=45)),
                ('diagnostico', models.TextField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(choices=[('Remitida', 'Remitida'), ('Proceso', 'Proceso'), ('Rechasada', 'Rechasada'), ('Terminada', 'Terminada')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_cabecera', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Toma_Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_formulacion', models.DateField(auto_now_add=True)),
                ('procedimiento', models.TextField(max_length=1000)),
                ('consuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='examenes')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('tipo_identificacion', models.CharField(choices=[('C', 'CC'), ('T.I', 'T.I'), ('Ex', 'CE')], max_length=45)),
                ('identificacion', models.CharField(max_length=45, unique=True)),
                ('tipo_doctor', models.CharField(choices=[('G', 'General'), ('E', 'Especialista')], max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('identificacion', models.CharField(max_length=45, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('C', 'CC'), ('T.I', 'T.I'), ('Ex', 'CE')], max_length=45)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=45)),
                ('estrato', models.CharField(choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=45)),
                ('nivel_educativo', models.CharField(choices=[('1', 'Basica Primaria'), ('2', 'Basica secundaria'), ('3', 'Tecnico'), ('4', 'Tecnologo'), ('5', 'Universitario'), ('6', 'Otros')], max_length=45)),
                ('tipo_paciente', models.CharField(choices=[('1', 'Cabeza familia'), ('2', 'Miembros')], max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('grupo_familiar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.grupo_familiar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.profesional'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.paciente'),
        ),
    ]
