# Generated by Django 3.1.2 on 2020-10-15 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Especialista_profecional',
            new_name='Grupo_Familiar',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='paciente',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='titulo',
            new_name='molestia_principal',
        ),
        migrations.RenameField(
            model_name='grupo_familiar',
            old_name='nombre',
            new_name='medico_cabecera',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='corro',
        ),
        migrations.RemoveField(
            model_name='toma_examen',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='toma_examen',
            name='examen',
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_familiar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.grupo_familiar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default=-1212, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='correo',
            field=models.EmailField(default=0.0008250825082508251, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(default=8.569444444444445, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toma_examen',
            name='fecha_formulacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='identificacion',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='tipo_doctor',
            field=models.CharField(choices=[('G', 'General'), ('E', 'Especialista')], max_length=45),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='examenes'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Grupo_Familia',
        ),
        migrations.DeleteModel(
            name='Solicitudes',
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.especialidad'),
        ),
    ]
